/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
/* Header for class example_dokemonster_ImageOLED */

#ifndef _Included_example_dokemonster_ImageOLED
#define _Included_example_dokemonster_ImageOLED
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_dokemonster_ImageOLED
 * Method:    open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_example_dokemonster_ImageOLED_open
  (JNIEnv *, jobject);

/*
 * Class:     example_dokemonster_ImageOLED
 * Method:    Control
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_example_dokemonster_ImageOLED_Control
  (JNIEnv *, jobject, jintArray);


#ifdef __cplusplus
}
#endif
#endif
