/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>

/* Header for class example_dokemonster_SimpleLED */

#ifndef _Included_example_dokemonster_SimpleLED
#define _Included_example_dokemonster_SimpleLED
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_dokemonster_SimpleLED
 * Method:    Open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_example_dokemonster_SimpleLED_Open
  (JNIEnv *, jobject);

/*
 * Class:     example_dokemonster_SimpleLED
 * Method:    TurnOn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_example_dokemonster_SimpleLED_TurnOn
  (JNIEnv *, jobject, jint);

/*
 * Class:     example_dokemonster_SimpleLED
 * Method:    TurnOffAll
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_example_dokemonster_SimpleLED_TurnOffAll
  (JNIEnv *, jobject);

/*
 * Class:     example_dokemonster_SimpleLED
 * Method:    Close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_example_dokemonster_SimpleLED_Close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
