/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
/* Header for class example_dokemonster_Segment */

#ifndef _Included_example_dokemonster_Segment
#define _Included_example_dokemonster_Segment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_dokemonster_Segment
 * Method:    SegmentControl
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_example_dokemonster_Segment_SegmentControl
  (JNIEnv *, jobject, jint);

/*
 * Class:     example_dokemonster_Segment
 * Method:    SegmentIOControl
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_example_dokemonster_Segment_SegmentIOControl
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
